
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: pgdev
    password: pgdev
    main.banner-mode: off

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true